### ISSUE TITLE
Google OAuth new Domains

### ISSUE THREAD

**Issue by maxgrove42** [gcivil-nyu-org/wed-fall24-team5#118]
We need to add the new domains to the Google OAuth

Definition of done: https://fooddonation-dev.com and https://fooddonation-prod.com have been added to the Google OAuth console.

**Comment by TekuriSaiAkhil** [comment]
Done. 
I had to remove Google auth support for HTTP elastic bean URLs which we had earlier because Google doesn't allow HTTP URLs along with HTTPS. 

That said, HTTP on local still works. So not a problem for local development.
