### ISSUE TITLE
View Completed Reservations: As a recipient I want to view my past orders that are completed so that I know the details of the orders I have placed before

### ISSUE THREAD

**Issue by TekuriSaiAkhil** [gcivil-nyu-org/wed-fall24-team5#16]
# Description:

Recipients should have access to a history of their completed orders, allowing them to review details such as the items they reserved, the donor, and the pickup details. This feature provides an overview of past interactions and helps users keep track of their past reservations.

# Acceptance Criteria:

- The recipient can navigate to a "Past Orders" section from their dashboard.
- The list of past orders includes:
  - Donation item(s)
  - Quantity
  - Pickup location and time
  - Donor (business/restaurant name)
- The recipient can view additional details for each order by clicking on the order entry.
- Completed orders are clearly marked as “Completed” or “Picked Up.”
- The recipient can filter past orders by date, donor, or food type to find specific reservations easily.
- The recipient receives a message if there are no past orders to display (e.g., “No completed orders found”).
- The system prevents further actions (such as modifying or canceling) on completed orders, but the recipient can still leave a review.

**Comment by QahtanAlJammali** [comment]
I believe this is done.
