### ISSUE TITLE
Site asks for location immediately, rather than waiting until clicking `Use My Location` button

### ISSUE THREAD

**Issue by maxgrove42** [gcivil-nyu-org/wed-fall24-team5#204]
We should only ask the user for their location when they click on "Use My Location" rather than immediately on site open.

**Comment by QahtanAlJammali** [comment]
If you wait long enough it should use your location without you clicking use my location. The geocoding takes a bit of time and I am guessing that is why it does not seem instant. 
Can you please open the page, make sure you accept that it uses your location and let me know if it picks up your location automatically and applies the 5 mile radius without you clicking the use my location?

**Comment by maxgrove42** [comment]
Sorry - I mean currently our application asks for your location right when you open the recipient dashboard page. I guess it sounds like that is expected behavior ! 

I was thinking that it should only prompt for permissions to use your location if the user clicks the `Use My Location` button on the search field, but it sounds like this isn't a bug, but rather expected behavior !

**Comment by maxgrove42** [comment]
Like I guess I was thinking it should only prompt for location permissions _if_ the user clicks the `Use My Location` UI button in the search field

**Comment by QahtanAlJammali** [comment]
Gotcha Max, so the workflow I will be working on next, is the site opens, with no location specific listings, then the user decides whether to hit the use my location button or enter a different address manually. 

**Previous flow:** site filters to items next to you automatically, then if you enter an address you can switch to that, and the use my location button was only there to go back to using your location.

Confirm and I'll make the change in a jiffy.

**Comment by QahtanAlJammali** [comment]
Awesome Thanks for the really quick response @maxgrove42 just put in a pull request, I want to make sure no tests break then will post in slack channel for review!

**Comment by TekuriSaiAkhil** [comment]
Cann we close this @QahtanAlJammali ?
