### ISSUE TITLE
Use more granular distances on Radius

### ISSUE THREAD

**Issue by maxgrove42** [gcivil-nyu-org/wed-fall24-team5#205]
Currently, Radius search on Recipient Dashboard only allows for a granularity of 5 miles. Since this is based for NYC, we should have more granular radii - say 0.5 mi, 1 mi, 2 mi, 5 mi, 10 mi, upwards

**Comment by QahtanAlJammali** [comment]
Great catch, this is totally more reasonable than the resolutions I put in. I can get that fixed asap.

**Comment by maxgrove42** [comment]
no rush imo !
