### ISSUE TITLE
Too many significant figures in the rating 

### ISSUE THREAD

**Issue by QahtanAlJammali** [gcivil-nyu-org/wed-fall24-team5#216]
**User story**
As a user I want to only see one or two significant figures. 

![Screenshot 2024-11-06 at 4 50 00 PM](https://github.com/user-attachments/assets/2654ee20-822c-4440-b51f-a80104369246)

**Acceptance criteria**
Significant figures reduced to 1 or 2

**Definition of Done**
Visually pleasing number of significant figures

**Comment by estchang** [comment]
This should be fixed in the latest PR to develop! Let me if you're still seeing this bug.

**Comment by maxgrove42** [comment]
This is closed right @QahtanAlJammali @estchang  ?

**Comment by estchang** [comment]
> This is closed right @QahtanAlJammali @estchang ?

Yep, gonna go ahead and close it
