### ISSUE TITLE
Popup modal headers occasionally not appearing

### ISSUE THREAD

**Issue by estchang** [gcivil-nyu-org/wed-fall24-team5#235]
The headers for the popup modals for edit reservation and edit review occasionally do not display. They usually appear correctly on the first few clicks, but after opening the modals enough times, they disappear and stay gone.

**Properly displaying:**
<img width="660" alt="Screenshot 2024-11-08 at 9 45 44 AM" src="https://github.com/user-attachments/assets/abe5a45c-5345-454e-bf30-dceaccde233e">

**Disappearing after a few clicks:**
<img width="653" alt="Screenshot 2024-11-08 at 9 46 09 AM" src="https://github.com/user-attachments/assets/56007f9d-c722-40c6-b3e3-2b77cea0dfa6">

**Comment by TekuriSaiAkhil** [comment]
This is the default bulma for 
<button class="delete"></button>
