### ISSUE TITLE
Replace "Alerts" with notifications

### ISSUE THREAD

**Issue by maxgrove42** [gcivil-nyu-org/wed-fall24-team5#237]
Alerts / Confirms (the popups from the browser) are an unappealing UX. They require the user to stop what they are doing on the site to dismiss the alert / confirm. We should replace all "alerts" / "confirms" with the implemented notification partial or a modal for a better User Experience

This issue serves as a running list of locations where we use "Alerts":
- [ ] Inability to access location

This serves as a running list of locaitons where we use "Confirms"
- [ ] Recipient Orders - Cancel Order
- [ ] Donor Dashboard - Make Organization Inactive

**Comment by arsalananwar11** [comment]
Wont be working on this as this is a part of optional enhancement
