### ISSUE TITLE
Canceled orders still show # Reserved

### ISSUE THREAD

**Issue by maxgrove42** [gcivil-nyu-org/wed-fall24-team5#240]
Canceled orders from the recipient side of things still show a number reserved. This is probably expected behavior since it draws from the order table, but this should likely display 0 reserved to minimize user confusion

<img width="1243" alt="Screenshot 2024-11-08 at 1 35 58 PM" src="https://github.com/user-attachments/assets/bce59399-6b84-4c81-81a2-9e75a5dc2302">

**Comment by TekuriSaiAkhil** [comment]
I think we should display the quantity canceled by the user, like 3 canceled, rather than displaying 0 reserved.
