### ISSUE TITLE
Google Authentication does not work

### ISSUE THREAD

**Issue by maxgrove42** [gcivil-nyu-org/wed-fall24-team5#248]
Google Log in and Register does not work. See screenshot. This occurs on the https://fooddonation-prod.com/ and https://fooddonation-dev.com/

<img width="1221" alt="Screenshot 2024-11-10 at 12 21 40 PM" src="https://github.com/user-attachments/assets/c5564d55-9019-4cb7-821f-08d168f42bf3">

<img width="374" alt="Screenshot 2024-11-10 at 12 22 25 PM" src="https://github.com/user-attachments/assets/a0c55010-2fac-4a94-86da-bcc48297d699">

**Comment by TekuriSaiAkhil** [comment]
Strange, It seems like an on-off thing. I got some idea of why this might be the case, but requires all the teams presence. Let's do an experiment on this tomorrow!!

<img width="1438" alt="Screenshot 2024-11-11 at 12 26 28 AM" src="https://github.com/user-attachments/assets/8db61c37-8732-4f09-8ace-a2f27838a448">

**Comment by maxgrove42** [comment]
- Running migrations after deployment should fix this issue. Max to update travis deployment pipeline.
