### ISSUE TITLE
Able to delete an already inactive organization

### ISSUE THREAD

**Issue by maxgrove42** [gcivil-nyu-org/wed-fall24-team5#259]
The delete button still shows up, even if an organization already has been deleted (marked as inactive). Can we switch this button to display as "Set to active" if the organization is already inactive / deleted?

<img width="1492" alt="Screenshot 2024-11-11 at 7 17 52 AM" src="https://github.com/user-attachments/assets/0451d523-6c4f-423b-9f0f-9e85d95b3f34">
<img width="1458" alt="Screenshot 2024-11-11 at 7 17 58 AM" src="https://github.com/user-attachments/assets/85264eda-a6c6-41d5-8cb7-c2a62c27536d">

**Comment by TekuriSaiAkhil** [comment]
Created a bug for it already. this is a duplicate. closing it.
https://github.com/gcivil-nyu-org/wed-fall24-team5/issues/263
