### ISSUE TITLE
[BUG] - Invalid Error for Invalid Email Sign Up Attempt

### ISSUE THREAD

**Issue by KartikeySharma** [gcivil-nyu-org/wed-fall24-team5#313]
**Summary**
When a user tries to sign up with an invalid email (eg. a@a), the error response they get says, "Registration Failed!! Password mismatch or too generic". However, I am entering the correct password both times (tried this like 5 times already).

**Steps to Reproduce**
- Go to Sign up page
- Enter an invalid email (I wrote `a@a`)
- Make sure the passwords match
- See the invalid error message

**Proposed Solution**
Implement a proper email regex with different error codes to make sure the user knows what the error actually is

**Additional Context (Screenshot & Recording)**
### Recording Link: [Passwords are the same for both error attempt and successful attempt in the recording](https://drive.google.com/file/d/1-YiniPfVTUdbKjsYurzWgzXekV_6aeNd/view?usp=sharing)

![image](https://github.com/user-attachments/assets/afc82651-6a70-4661-b548-ec48972fdaca)

**Alternatives Considered (optional)**
Email Regex should be robust and handle error messages properly

**Comment by maxgrove42** [comment]
Thanks - accepted and will work through!
