### ISSUE TITLE
[BUG] - Improve User Flow After Login

### ISSUE THREAD

**Issue by deepjyotk** [gcivil-nyu-org/wed-fall24-team5#314]
**Description**
 Improve User Flow After successful Login. 
**Steps to Reproduce**
1. User logs in.
2. Lands on the homepage.
3. Clicks the back button and attempts to log in again.
4. Sees 403 forbidden page, Poor user experience occurs. 
**Expected Behavior**
(Consider redirecting the user to the main page after a successful login to prevent them from navigating back to the login screen.)
**Screenshots or Code Snippets (required)**
<img width="1710" alt="image" src="https://github.com/user-attachments/assets/19424d6d-879c-4437-9eb7-2ea37c691384">

**Comment by maxgrove42** [comment]
I'm having trouble recreating this bug, both in Safari and Brave, and incognito tabs in both of those browsers. 

@deepjyotk What browser are you using? 

We currently have checks in place to redirect to the recipient dashboard if user is logged in.

https://github.com/gcivil-nyu-org/wed-fall24-team5/blob/3dfeac940bcd065c2d6f5701377d83ca6492dc5b/src/accounts/views.py#L77-L79

https://github.com/gcivil-nyu-org/wed-fall24-team5/blob/3dfeac940bcd065c2d6f5701377d83ca6492dc5b/src/accounts/views.py#L46-L48

**Comment by deepjyotk** [comment]
Hey @maxgrove42, I’m using Chrome. After logging in, I clicked the back button, which took me back to the login page. I tried logging in again, but it led me to the attached page.

**Comment by maxgrove42** [comment]
Got it - it looks like Chrome, this does occur on. It looks like the page is being cached in Chrome, vs Brave and Safari don't cache the page. I'll investigate further.

**Comment by maxgrove42** [comment]
Thanks!

**Comment by arsalananwar11** [comment]
Thanks again for reporting this! But closing this for the following reasons:
- Limited scope (not how the user behaves typically)
- Issue limited to few browsers (debugging this and fixing doesnt add significant value to the project)
