### ISSUE TITLE
[BUG] - Phone Number is set to a string "None" by default

### ISSUE THREAD

**Issue by KartikeySharma** [gcivil-nyu-org/wed-fall24-team5#316]
**Summary**

- Phone Number is set to `"None" `by default and is not accepted as a valid response even though its auto populated
- As a user, I would rather have the liberty of not sharing my phone number unless I HAVE to (in this case, the application should mark it as a required variable)

**Steps to Reproduce**
- Login
- Go to Profile
- You should see Phone Number autopopulated with **None**
- Try changing any other fields (not needed)
- Try clicking on "Update your Profile"
- User will get an error message saying that "Please match the requested format"

**Proposed Solution**
Make sure that the first time a user opens the profile, the Phone Number is set to empty instead of `None`

**Screenshot**
Recording Link:  [I would expect the Phone Number to be Empty if it is not required ](https://drive.google.com/file/d/1To4HCspcza3hrQbI8fvUztc8uwTdTIqs/view?usp=sharing)

![image](https://github.com/user-attachments/assets/a75c85b5-7010-4509-97ce-cfe7b03a879e)

## Note: This bug will not be reproducible specifically for test user 5 because after taking the recording a screenshot, I cleared Phone number to be empty to check if that is saveable (and yes it was)

**Comment by maxgrove42** [comment]
Thanks - accepted and will work through!
