### ISSUE TITLE
[BUG] - Potential CSV Injections

### ISSUE THREAD

**Issue by aakashshankar** [gcivil-nyu-org/wed-fall24-team5#318]
**Description**
I see that you have a view called download_orders for the donor_dashboard app, which downloads orders of an organization into a CSV. The entries that get populated in this csv are not properly sanitized. I can craft a malicious food item like `=DDE(\"cmd\";\"calc\";\"\")"`, which is interpreted by CSV readers (like MS Excel) to run arbitrary commands.

**Steps to Reproduce**
Go to the Organizations tab, aka your "donor dashboard". Add a donation for an item like this, =DDE(\"cmd\";\"calc\";\"\") which is an excel formula that can run arbitrary commands on its host machine. Reserve this item so that it shows up on the organization's "Orders" tab. Download orders for this organization using the `download_orders` view. Open the CSV that's downloaded. (for 100% of windows users, that would be excel).

**Expected Behavior**
Your inputs *must be sanitized* before you export it to CSV. Maybe something like,
```python
def sanitize_csv_value(value):
    if value is None:
        return ""
    
    # Convert to string
    value = str(value)
    
    # List of potentially dangerous prefixes
    dangerous_prefixes = ['=', '+', '-', '@', '\t', '\n']
    
    # If value starts with any dangerous prefix, prepend a single quote
    if any(value.startswith(prefix) for prefix in dangerous_prefixes):
        value = f"'{value}"
    
    return value
```

**Screenshots or Code Snippets (required)**
<img width="943" alt="Screenshot 2024-11-14 at 12 17 23 AM" src="https://github.com/user-attachments/assets/4413252b-db72-40f1-9792-bb89d3fad7e2">

<img width="776" alt="Screenshot 2024-11-14 at 12 18 18 AM" src="https://github.com/user-attachments/assets/0741ee5d-86d7-4f00-9fe3-c6b8a6797c8a">

<img width="355" alt="Screenshot 2024-11-14 at 12 18 35 AM" src="https://github.com/user-attachments/assets/70f41925-a85b-4826-a111-155fb9c2b8ac">

**Additional Context (optional)**
There wasn't any info in your testing doc about this functionality, so I decided to report this.

**Comment by maxgrove42** [comment]
This is actually a great find
