### ISSUE TITLE
[BUG] - Organization can change a canceled order into pending/complete

### ISSUE THREAD

**Issue by omerfarukbasar** [gcivil-nyu-org/wed-fall24-team5#319]
**Description**
After a recipient cancels an order they reserved, an organization can go back and change the status of the order back to pending or completed. If changed to complete, it will not decrement the available item count, while still counting towards analytics. Also, canceled ordered are seen as completed orders on the organization dashboard, offering no distinction between actual completed orders and canceled one.

**Steps to Reproduce**

1. As a recipient, go reserve an item
2. Cancel the reservation
3. As an admin for the organization, go to the dashboard
4. See the specific order from the recipient, and notice its marked as complete despite being canceled
5. Click to change the status from canceled to pending
6. It can also be taken a step further and be marked as complete
7. On the recipient end, you can see the order moved from canceled to pending or complete.
8. On the organization end, if you had changed the order to complete, the item amount does not decrease, going back to what it was prior to the order. 

**Expected Behavior**
Organizations should not be able to uncancel an order.  Canceled orders should also be communicated properly on the organization dashboard. Even if an order is changed from uncanceled to complete, the item count should update to its correct amount.

**Screenshots or Code Snippets (required)**

Initial organization item with count
<img width="1280" alt="Screenshot 2024-11-14 at 12 12 21 AM" src="https://github.com/user-attachments/assets/f866023a-80dd-4d24-b40b-e8f5d4b82ab7">

Reserve an item as a recipient
<img width="1280" alt="Screenshot 2024-11-14 at 12 14 35 AM" src="https://github.com/user-attachments/assets/d0a45e71-02ef-4a27-abf2-34c41ead0b7b">

Cancel reservation as recipient
<img width="1280" alt="Screenshot 2024-11-14 at 12 15 02 AM" src="https://github.com/user-attachments/assets/bf2707ac-00b9-441f-8cb4-e5dad8182bac">

See order is marked complete on organization dashboard despite cancelation
<img width="1280" alt="Screenshot 2024-11-14 at 12 15 28 AM" src="https://github.com/user-attachments/assets/b7f781a4-5fa9-4771-bb45-8a24049f4f03">

Organization can change it to pending
<img width="1280" alt="Screenshot 2024-11-14 at 12 15 41 AM" src="https://github.com/user-attachments/assets/74a2683a-6a9a-4e4e-81a6-4022c94376ed">

As user, you see order is no longer in cancel, its in pending
<img width="1280" alt="Screenshot 2024-11-14 at 12 16 09 AM" src="https://github.com/user-attachments/assets/004b7b68-935c-428a-8d7c-dd4b2b07d9a4">
<img width="1280" alt="Screenshot 2024-11-14 at 12 16 13 AM" src="https://github.com/user-attachments/assets/74d285ac-4514-4b9d-97e8-4db9bc41b97f">

As org, you can again change it to complete
<img width="1280" alt="Screenshot 2024-11-14 at 12 16 43 AM" src="https://github.com/user-attachments/assets/39205352-587d-4288-b324-4e9af41eeb50">

The item count will not change even as marked as complete
<img width="1280" alt="Screenshot 2024-11-14 at 12 16 51 AM" src="https://github.com/user-attachments/assets/aff6063e-eb2b-4417-87d6-864bea6fcd31">

On recipient end it is marked as complete
<img width="1280" alt="Screenshot 2024-11-14 at 12 17 18 AM" src="https://github.com/user-attachments/assets/3e71d008-1172-4548-b7df-9f7ba95af4ff">

**Comment by maxgrove42** [comment]
Thanks - accepted and will work through!

**Comment by arsalananwar11** [comment]
Thanks @omerfarukbasar for reporting this! Good find!
