### ISSUE TITLE
[BUG] - Recipients with no name can make reservations

### ISSUE THREAD

**Issue by omerfarukbasar** [gcivil-nyu-org/wed-fall24-team5#320]
**Description**
As a recipient, I can edit my profile to remove my first and last names. Then I can go and reserve an item. On the organization's end, when viewing the order, there is no indication on who the order is for.

**Steps to Reproduce**

1. As a recipient, go edit your profile and remove the name fields
2. Go reserve an item from an organization
3. As an organization, go to orders and see an order with no name

**Expected Behavior**
As an organization, if a recipient has no name, their email should be displayed as a form of identification. The other solution would be to enforce having a first & last name as part of a profile.

**Screenshots or Code Snippets (required)**

Recipient profile:
<img width="1280" alt="Screenshot 2024-11-14 at 1 35 05 PM" src="https://github.com/user-attachments/assets/625afacf-7c3a-4d12-b396-0499d1e3aa4c">

Organization's view:
<img width="1280" alt="Screenshot 2024-11-14 at 1 38 08 PM" src="https://github.com/user-attachments/assets/f44acc26-6af7-4db8-84b7-9f3cdbf3f323">

**Comment by maxgrove42** [comment]
Thanks - accepted and will work through!
