### ISSUE TITLE
[BUG] - Organizations can add duplicate donation items for the same day

### ISSUE THREAD

**Issue by shub-garg** [gcivil-nyu-org/wed-fall24-team5#321]
## Description
Organizations are able to add multiple instances of the same donation item on a single day, leading to duplicate entries. This issue affects inventory tracking and reporting by causing confusion and inaccurate data.

## Expected Behavior
When an organization attempts to add a donation item that already exists for the same donation day, the system should:

- Detect the duplicate entry based on predefined criteria (e.g., Item Name and Date).
- Prevent the addition of the duplicate item.
- Display an informative message to the user, such as "This donation item has already been added for [specific day]."
- Optionally, increment the quantity of the existing item in the database instead of creating a duplicate entry.

## Steps to Reproduce
1. Log in to the application as a user.
2. Navigate to the **Organization** section from the dashboard.
3. Click on the **View Organization** button.
4. Click on the **Add Donation** button.
5. Enter the donation details (e.g., Item Name: "Apples", Quantity: 100, Date: [a date when "Apples" are already listed]).
6. Submit the donation.
7. Repeat steps 3-5 with the same donation details (e.g., Item Name: "Apples", Quantity: 100, Date: [the same date]).
8. Observe that both donation entries are successfully added without any warnings or restrictions.

## Actual Behavior
The system allows multiple donation entries with identical details to be added on the same donation day without any validation or warnings, resulting in duplicate records.

## Screenshots
![Duplicate Donation Entries](https://github.com/user-attachments/assets/a96cd6bf-e8c6-4992-a97f-2d871b88921a)

## Impact
Duplicate donation entries lead to inaccurate inventory counts and reporting issues, which can affect resource allocation and decision-making processes.

## Possible Solution
Implement a server-side validation check to verify if a donation item with the same name and date already exists before allowing a new entry. Additionally, provide user feedback to inform them about the duplicate entry attempt. Alternatively, consider updating the quantity of the existing donation item instead of creating a duplicate entry.

---

**Comment by arsalananwar11** [comment]
Hey @shub-garg, we appreciate you testing our application. I think this is more of a design choice. There is a possibility that there might be different batches of the same item listed, so the current design stands.

**Comment by shub-garg** [comment]
![image](https://github.com/user-attachments/assets/1ee255c0-f003-44e8-8921-3bc5608da119)


I understand, but then which one should the user book? Isn't it too confusing for the user to see the donation for the same item for the same timestamp by the same organization? Also the organization won't know how to manage their own inventory seeing two copies of the same thing at the same time stamp. Would be better if you add it as a single item or at least provide some distinction between them.

## Also:

![image](https://github.com/user-attachments/assets/93ed5d50-7c1a-4efd-b2b5-1475833fb119)


Allowing for duplicates the user is able to overcome the "You cannot reserve more than 3 of the same item." as shown in the image, making it even more confusing for both the organization and the user and breaking a core restriction placed by the website admins. This seems to be a separate bug, but I will leave it here as it appears to be related to this issue.

**Comment by maxgrove42** [comment]
Team discussion: Add a `created on: ` tag to display on the card.
