### ISSUE TITLE
[SUGGESTION] - Validation on add organization input fields

### ISSUE THREAD

**Issue by soniasusanto** [gcivil-nyu-org/wed-fall24-team5#325]
**Summary**
Adding an organization currently does not validate if it is a valid organization. 

**Proposed Solution**
You may want to consider validating address, e.g. it needs to be a valid NY address. You could also add validation for phone numbers.

**Additional Context (optional)**
<img width="914" alt="Screenshot 2024-11-14 at 9 15 39 PM" src="https://github.com/user-attachments/assets/4ce72ee8-4b7c-431d-a03d-190db41058ca">

**Comment by maxgrove42** [comment]
This is a great suggestion. We have form validation in other places so we'll add it here as well.

**Comment by maxgrove42** [comment]
Marking as closed due to #338
