### ISSUE TITLE
[SUGGESTION] - allow user to submit ratings

### ISSUE THREAD

**Issue by soniasusanto** [gcivil-nyu-org/wed-fall24-team5#326]
**Summary**
Ratings on the dashboard appear static today. Clicking on the rating takes me to google maps instead. It is not clear how ratings are determined and if the user is able to submit one to influence the rating. 

**Additional Context (optional)**
<img width="1399" alt="Screenshot 2024-11-14 at 9 28 44 PM" src="https://github.com/user-attachments/assets/d47e7957-5326-4bfb-a903-e02438a22576">

**Comment by maxgrove42** [comment]
Hey Sonia @soniasusanto - great question / suggestion. Ratings are the aggregate of donations made when a recipient picks up an order. Once an order is marked as "picked up," a recipient can review the donation. Then, the organization stars represent the aggregate of all reviews for all donations they have provided.

We'll think through a way to make this clearer.

<img width="1512" alt="Screenshot 2024-11-15 at 8 09 46 AM" src="https://github.com/user-attachments/assets/8977847f-0a48-4646-9f4e-e9be55cf506d">
<img width="1512" alt="Screenshot 2024-11-15 at 8 09 42 AM" src="https://github.com/user-attachments/assets/cfde8d5e-5020-45fb-bd39-be623eb74fda">

**Comment by arsalananwar11** [comment]
Closing this because this is already addressed! Thanks again for adding this!
