### ISSUE TITLE
[BUG] - Exceeding character count on modify donation causes Server Error (500)

### ISSUE THREAD

**Issue by omerfarukbasar** [gcivil-nyu-org/wed-fall24-team5#327]
**Description**
As an organization, when you modify a donation, if you type 300 or more characters into the food item field and then hit submit, it will cause a Server Error (500) to appear.

**Steps to Reproduce**
1. As an organization, go to the donations tab
2. Click on modify for any food item
3. In the food item field, enter 300 or more characters and hit submit
4. Observe the Server Error (500) message appear

**Expected Behavior**
It should not lead to a Server Error (500). Instead have it display that the operation was not successful. I believe something like this is already prepared for other areas like editing profile. A character limit could also be communicated for text fields.

**Screenshots or Code Snippets (required)**
<img width="1280" alt="Screenshot 2024-11-15 at 12 10 26 AM" src="https://github.com/user-attachments/assets/5f77f368-ef69-44ce-bfd3-c3e41d538a80">
<img width="1280" alt="Screenshot 2024-11-15 at 12 11 03 AM" src="https://github.com/user-attachments/assets/4cb7eafa-7df4-41df-afc8-81177d455c54">

**Comment by arsalananwar11** [comment]
Hey @omerfarukbasar, thanks for pointing this out. We will work on this issue!

**Comment by shub-garg** [comment]
Same issue with Quantity, enter a bug quantity in modify item, leads to 500 server error.

**Comment by arsalananwar11** [comment]
> Same issue with Quantity, enter a bug quantity in modify item, leads to 500 server error.

Thanks @shub-garg for pointing this out! Really appreciate it! Can you create a separate issue (bug report) for this?
