### ISSUE TITLE
[BUG] - Exceeding character counts on manage organization does not do anything

### ISSUE THREAD

**Issue by shub-garg** [gcivil-nyu-org/wed-fall24-team5#328]
## Description  
When editing the name of an organization, if the user enters a name exceeding 300 characters, the web app does not do anything. For shorter names, the application updates the name and navigates the user back to the previous page with the updated name. However, for names longer than 300 characters, the app neither updates the name nor provides an error message, leaving the user with no feedback. 

Also in manage organization, the user is able to enter alphabets like "e" in the phone number section which should not be allowed.

---

## Steps to Reproduce  
1. Navigate to the **Organizations** section.  
2. Click on **Manage Organizations**.  
3. Attempt to edit an organization's name by entering a name exceeding 300 characters.  
4. Observe that the application does not respond or provide any error message.

---

## Expected Behavior  
The application should either:  
1. Accept the input if the system supports names longer than 300 characters, update the name, and redirect the user back to the previous page.  
2. Display a clear error message stating that the name exceeds the character limit (e.g., "Name cannot exceed 300 characters").  

This feedback ensures that users understand why their input was not accepted.

---

## Screenshots or Code Snippets (required)  
![Bug](https://github.com/user-attachments/assets/e6240595-4911-4258-993a-cb53f52b5973)
---

**Comment by arsalananwar11** [comment]
Hey @shub-garg, thanks for submitting the report but I see the name getting updated properly on top (Hi gets replaced with 'Lorem ipsum...'. Attaching a snippet from your video for reference.

However, we will consider implementing character limits on all the fields as an enhancement (also pointed out in a similar issue earlier). 

![image](https://github.com/user-attachments/assets/d554645a-cab1-4f0a-af0a-880de8d489ae)

**Comment by shub-garg** [comment]
Yes it is there, but as soon as you go back it is still Hi. So it seems it is being updated only on front end for a moment
