### ISSUE TITLE
[BUG] - Entering Quantity Greater Than 10 Digits Causes Server Error 500

### ISSUE THREAD

**Issue by shub-garg** [gcivil-nyu-org/wed-fall24-team5#329]
**Description**
When modifying a donation, if the user enters a quantity exceeding 10 digits, the application encounters a server error (HTTP 500). This issue prevents the update from being saved and disrupts the user workflow.

## Steps to Reproduce  
1. Navigate to the **Donations** section.  
2. Select an existing donation and click **Modify Donation**.  
3. In the quantity field, enter a value exceeding 10 digits (e.g., `99999999999` or greater).  
4. Submit the form and observe that the application throws a server error (HTTP 500).

## Expected Behavior  
- The application should validate the quantity field and prevent users from entering values exceeding the allowable range.  
- If the quantity exceeds the system limit, display a clear error message (e.g., "Quantity cannot exceed 10 digits.") without crashing the server.  

This ensures proper handling of invalid inputs and maintains system stability.

**Screenshots or Code Snippets (required)**
![image](https://github.com/user-attachments/assets/fa288aea-24de-4e1d-abbb-db119bf61841)

![image](https://github.com/user-attachments/assets/e2ed3e06-a2eb-4f7a-9941-c1b88349ce7d)

**Comment by arsalananwar11** [comment]
Good find, thanks @shub-garg! Appreciate you testing our application and helping us improve it!
