### ISSUE TITLE
[BUG] - Unable to create a new organization

### ISSUE THREAD

**Issue by thejaswinidm** [gcivil-nyu-org/wed-fall24-team5#333]
**Description**
When the input fields do not match a certain unknown criteria, the add organization feature doesn't work.
It does not show any error on the screen as well.

**Steps to Reproduce**
Ex:
1. Go to Add organization and enter the details as shown in the screenshot below, the organization doesn't get created neither there is an error displayed.

**Expected Behavior**
An error message showing why the org was not created would be great for the user to rectify their mistake.

**Screenshots or Code Snippets (required)**
<img width="1078" alt="Screenshot 2024-11-15 at 7 40 22 PM" src="https://github.com/user-attachments/assets/c17b0c2e-5e48-437a-b701-fc171fa5cd1a">

**Comment by maxgrove42** [comment]
Here, the email isn't valid - We'll implement format checking and error messages :) . thanks for the find!
