### ISSUE TITLE
Database Setup for Community Drives

### ISSUE THREAD

**Issue by maxgrove42** [gcivil-nyu-org/wed-fall24-team5#349]
As developers, we need to have databases set up for the community drive feature.

# Acceptance Criteria
- Database documentation has been described in this ticket.
- Models have been updated in `models.py`
- Tests have been added
- Migrations have been run.

**Comment by maxgrove42** [comment]
# Database Models

## Community Drive
- UUID, name, description, creator (organization foreign key), deadline_date, is_active, created_at, modified_at

## Participating Organization
- UUID, community drive (foreign key), organization (foreign key), meal pledge (integer), volunteer pledge (integer), created_at, modified_at
  - Are tracking the volunteers and meals they contribute (i.e. do we need tables for volunteers and donations) or is this just to account for the numbers?

@arsalananwar11 @takhilabhinav @QahtanAlJammali @estchang any comments here? 

Arsalan - know in your wireframe you indicated images. I think let's add that in after we get through the initial period / if time allows? 

Could have a table like:
- **DriveMedia:** Media UUID, community drive (foreign key), imagefield, caption, uploaded_at, uploaded_by (user_id)

**Comment by arsalananwar11** [comment]
> # Database Models
> ## Community Drive
> * UUID, name, description, creator (organization foreign key), deadline_date, is_active, created_at, modified_at
> 
> ## Participating Organization
> * UUID, community drive (foreign key), organization (foreign key), meal pledge (integer), volunteer pledge (integer), created_at, modified_at
>   
>   * Are tracking the volunteers and meals they contribute (i.e. do we need tables for volunteers and donations) or is this just to account for the numbers?
> 
> @arsalananwar11 @takhilabhinav @QahtanAlJammali @estchang any comments here?
> 
> Arsalan - know in your wireframe you indicated images. I think let's add that in after we get through the initial period / if time allows?
> 
> Could have a table like:
> 
> * **DriveMedia:** Media UUID, community drive (foreign key), imagefield, caption, uploaded_at, uploaded_by (user_id)

Regarding Tables: Everything looks good. I also think its important to store information about the volunteers (name, email, phone number). For donations, just the pledge number should be enough

Regarding the images: Yes, we can first set this up and then focus on the images (although images shouldnt take much time)
