### ISSUE TITLE
[SUGGESTION] - After registering, display a set of instructions as a pop up modal

### ISSUE THREAD

**Issue by maxgrove42** [gcivil-nyu-org/wed-fall24-team5#358]
**Summary**
- Add a `Help` page that displays helpful information

**Problem Statement**
- This could help users who want to use a specific part of our site but don't want to spend too much time clicking around to figure it out.

**Proposed Solution**
- 3 tabs -> One for a recipient, one for a donor, and one for community drives.

### Recipient
  - Homepage is the donations page. You can search for items here and reserve them. 
  - You should coordinate directly with the organization for pickup. 
  - You can also view your statistics by clicking the `View My Stats` page
  - Once you make reservations, you can view them on the `Reservations` page. Here, you can mark your order as picked up and then review the food item! You can also cancel or modify reservations you have not picked up yet.
  - You can edit your profile and set dietary restrictions on the `Profile` page.
  - Feel free to send messages to donors on the `Messages` page to ask them more questions.
  - This page can be viewed later under the `Help` page!
### Donor
  - You can access your donations on the `Organizations` tab. All donations must be made through an organization, but the organization can just be yourself!
  - On the `Organizations` page, you can view your existing organizations or add an Organization.
  - By viewing an existing organization, you can add donations, view your active donations, view your pending orders, download all your orders (pending, picked up, and cancelled), or view your reviews.
    - If you are an "owner" of the organization, you have special privileges. You can edit the organization details, add other administrators or owners to your organization, or deactivate the organization
  - You can also view statistics about this organization my clicking `View all` next to statistics.
  - You can view your organization's incoming messages by clicking `Messages` on the Manage Organization page.
  - This page can be viewed later under the `Help` page!
### Community Drive
  - TBD once we have this set up
  - This page can be viewed later under the `Help` page!

**Comment by arsalananwar11** [comment]
Can we also create product tours for new users which will show the user each functionality of the app

Reference Link: https://www.chameleon.io/blog/javascript-product-tours

Reference Snippets:
![image](https://github.com/user-attachments/assets/7e024983-d6a9-4685-a124-cf475f4d5599)

![image](https://github.com/user-attachments/assets/5d795aae-d2fd-4722-9fb8-0890dd841f9a)

**Comment by maxgrove42** [comment]
@arsalananwar11 I didn't see your comment until after i started work on this. Let's discuss on Monday !
