### ISSUE TITLE
Backend System Design

### ISSUE THREAD

**Issue by TekuriSaiAkhil** [gcivil-nyu-org/wed-fall24-team5#4]
Documentation for Backend System Design:
https://docs.google.com/document/d/1D-URZTSsWRJyqOTM7TI6t5RqxEnKYNDtQiZWb7VHoiM/edit?usp=sharing

**Comment by QahtanAlJammali** [comment]
Looks good so far.

**Comment by maxgrove42** [comment]
I like that you added a `orders` database. I'll add that to my [Data Flow Diagram](https://github.com/gcivil-nyu-org/wed-fall24-team5/blob/1592e861c822ac5f5e82cb53ad258a78f649ea39/DesignDocs/DataFlowDiagram-1.png).

I marked `userPreferences` as its own database - what do you think @TekuriSaiAkhil ?

**Comment by maxgrove42** [comment]
Once we finalize this - let's open a Pull Request to merge the `pdf` file into the `DesignDocs` folder (that folder will exist once I merge [my PR for Use Case and Data Flow diagrams](https://github.com/gcivil-nyu-org/wed-fall24-team5/pull/3)

**Comment by TekuriSaiAkhil** [comment]
> I like that you added a `orders` database. I'll add that to my [Data Flow Diagram](https://github.com/gcivil-nyu-org/wed-fall24-team5/blob/1592e861c822ac5f5e82cb53ad258a78f649ea39/DesignDocs/DataFlowDiagram-1.png).
> 
> I marked `userPreferences` as its own database - what do you think @TekuriSaiAkhil ?
> 
> Otherwise, looks great. I'm in agreement with all of this.

Yup `userPreferences` should be a table of its own. I'll update the document.
