### ISSUE TITLE
Create Database Schema Design by defining Tables, Relationships and Datatypes

### ISSUE THREAD

**Issue by arsalananwar11** [gcivil-nyu-org/wed-fall24-team5#58]
## Description
Design the database schema including tables, relationships, primary/foreign keys, and indexes.
## Tasks:

- Define tables: Eg: Users, Organizations, OrganizationAdmins, Donations, Messages, etc.
- Define relationships between tables, ensuring foreign key integrity.
- Identify fields for each table (including created_at, modified_at).
- Plan indexing for frequent queries (e.g., by org_id, donation_id)

## Deliverable: 
Complete database schema design and get it verified by the broader team

**Comment by arsalananwar11** [comment]
Database Schema: https://docs.google.com/document/d/1Ffxq0YF8IEdyU8buVlh1Ki1xRW3IMANy3fVDI3F5bMI/edit#heading=h.ga90jsut29rn

**Comment by maxgrove42** [comment]
**Really** great work with this. IMO it helps a lot to have it written out. Thanks Arsalan!

**Comment by QahtanAlJammali** [comment]
Here is the Entity-Relationship Diagram: https://dbdiagram.io/d/foodappDB-67052341fb079c7ebdbbda6b
Here is a PDF version: https://drive.google.com/file/d/133NMObeX6Gka26ofFjfQxkb1rpa6napF/view?usp=drive_link

**Comment by arsalananwar11** [comment]
> Here is the Entity-Relationship Diagram: https://dbdiagram.io/d/foodappDB-67052341fb079c7ebdbbda6b Here is a PDF version: https://drive.google.com/file/d/133NMObeX6Gka26ofFjfQxkb1rpa6napF/view?usp=drive_link

@QahtanAlJammali - Do you want to have another task for the ER Diagram and tag it under the Database User Story within this Milestone?
