### ISSUE TITLE
UI/UX Wireframe

### ISSUE THREAD

**Issue by estchang** [gcivil-nyu-org/wed-fall24-team5#6]
## User story
As a software engineer, I want to create an interactive wireframe that shows the tentative UI of the system's frontend so that the team can visualize the system's features.

**Acceptance criteria**
- All essential user interactions and flows within the application have been mocked up
- There are no broken flows

**Definition of Done**
- Team has reviewed and approved the wireframe

#### Landing Page
<img width="700" alt="Landing Page" src="https://github.com/user-attachments/assets/1fecf2e8-0f0b-475c-bb4b-fe327513a1eb">

#### Recipient Dashboard
<img width="652" alt="Recipient Dashboard" src="https://github.com/user-attachments/assets/7e66ce1b-2ae8-4a64-9991-8e69b4e0f12f">

#### Donor Dashboard
<img width="652" alt="Donor Dashboard" src="https://github.com/user-attachments/assets/b2308186-dedf-4659-9f4b-3de5661ed06b">

### Pages not pictured above:
- Messages
- User management for donor organizations
- Order management
- Login modal
- Add/delete/edit listing modals

### Overall Flow
<img width="805" alt="Figma Flow" src="https://github.com/user-attachments/assets/14af7a60-cf6e-41ac-882f-e45f0f13082f">

**Comment by maxgrove42** [comment]
This is great. Nice Work, @estchang .

**Comment by arsalananwar11** [comment]
Great job @estchang! The initial wireframes look great
